name: Deploy to cPanel Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Deploy via FTP to hosting
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.hoavosacstore.id.vn
          username: rddpneqo
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
          dangerous-clean-slate: false    